### ISSUE TITLE
Better molecule representation

### ISSUE THREAD

**Issue by maxhodak** [maxhodak/keras-molecules#31]
Using SMILES makes this problem unnecessarily hard, likely detracting from the smoothness of the latent space and causing the majority of sampled SMILES to be invalid even after extended training. The graph convolution work isn't reversible so you can't use it to generate new structures not in the initial set. This is pretty open-ended but what are other representations to try? Ideally somewhere where every point corresponds to a valid molecule.

One idea I've had is to borrow on the concept of cellular encodings, where rather than specifying the molecular graph directly we specify a set of operations which when evaluated yield a valid molecule. Then we're doing seq-to-seq learning for a list of "molecule construction ops." Careful thought would have to be put into the instruction set, but I think it might be possible to get something expressive where every combination is also valid.

@dakoner ?

**Comment by dakoner** [comment]
I'd have to think pretty deeply on this for a while to provide a real contribution.  A few things, though.  Pharma chem-space is huge- 10**60 to 10**63-- and unfortunately, its size can't be easily determined without direct enumeration.

The idea of using a state machine to produce chemicals already seemed attractive to me.  I was wondering if it was possible to make a state machine that sampled chemical space (either enumeratively, by iterating over each possible state sequence), and further, if it was possible to recover the internal state that emitted a molecule.  If the internal states can be represented as integers, then you might be able to encode the state vector using a prime number encoding (like a Godel numbering, but for chemicals instead of molecules). Then recovering the state vector for an encoding is a matter of prime factorization- expensive.  I see some other mentions of reversible grpah encodings.

Another idea is to convert the SMILES string to a molecular graph, and encode it via the connectivity or distance matrix, using the diagonal of the matrix to store element number.   

I think there are some "hard" CS problems here- if you have a way to reversibly encode a graph to a number space, it implies you've solved the graph isomorphism problem (because two graphs could be encoded to integers and then compared via integer equality).  

as for the molecule construction ops, I assume the GDB people already do this?
http://pubs.acs.org/doi/abs/10.1021/ci300415d
Since GDB is a direct enumeration and includes "all" compounds one there is probably some interesting underlying generator- apparently, they just generate "all possible graphs with up to N vertices", substitute in various atoms according to the valency rules, and then expand substituents off the scaffold.

**Comment by pechersky** [comment]
I've also thought a lot about this and better model training. I'd love to hear your thoughts on what's possible and what's worth prioritizing.

A SMILES string is approximately a depth-first tree representation of the molecular graph. Instead, one could imagine a breadth-first approach, like you suggest with a state machine. At every iteration of the machine, the previously generated tree/sequence would be promised to be a valid compound. The sequence itself wouldn't be very human-readable, but a better representation for the NN. For example, instead of writing out solely the nodes (atoms), with sparse bond info, you would write the nodes, as well as how many bonds stem from that node. You travel in one direction across a tree, with the sequence being (nodes)-(edges)-(next nodes)-(next edges)-... . There would have to be an additional "fusion" edge operation that allows the closing of cycles.

I've started playing with this. I've switched my model training to work on a generator -- this way, I can train on a potentially infinite set that samples "known" molecules randomly. Given a SMILES, it can generate an on-the-fly rotation and re-representation of it.

Thanks for bringing up the GDB set. I've tried plugging in the GDB-13 hydrocarbon compounds into a trained model -- it did not do well. For example, it gets confused on simple `C`: methane, or on highly cyclic compounds. I've begun reading about "curriculum training", with the idea being that first, the model is trained on just hydrocarbon graphs, such that it learns how to encode connectivity. Then, more latent dimensions are added, and the model is trained on compounds that now incorporate valence and atom type information. I haven't had a chance to make this work yet.

I also agree that providing the adjacency matrix that represents the graph might help the network, since it would have "global" access to upcoming nodes. Would the NN architecture use Conv layers or RNN layers to encode it? Would it be possible to reconstruct an adjacency matrix from latent space? Could one use the new "deconvolution" layers to do so? I also don't think that encoding atom identity on the diagonal is worth it, it is data which is very much unlike the rest of the matrix, and would mess with the convolutions.

Other things I've implemented and found useful, or will soon:
- using ELU instead or ReLU for the conv layers has led my networks to get trained quicker and without divergence
- one-hot encoding things like `Cl` and `[NH+}` as a separate token has also worked, not sure yet which approach is better
- currently trying "infinite" training generator combining several compound sets
- planning on trying "curriculum learning" based on GDB set
- planning on trying on-the-fly generation of non-canonical SMILES
- planning on trying training on adjacency matrices
- planning on trying adversarial training, with a "validity" classifier -- feed invalid representations back into the network with an "invalid" classifier
- planning on trying non SMILES string representations of compounds

**Comment by maxhodak** [comment]
> one-hot encoding things like Cl and [NH+} as a separate token has also worked,

I'm not a fan of hand-engineering these, but one thing you might do is try something like building a Huffman code to automatically pull out frequently reused structure from the string.

**Comment by pechersky** [comment]
What's the downside of increasing the "charset" size? My inclination comes from the fact that we feed the SMILES into a conv layer, so any increase in string size disrupts the converged kernels. There shouldn't really be a difference between `CCCC` and `CCCCl`, since each encodes 4 heavy atoms, but the string is markedly different. One-hot encoding `Cl` and such helps by making single-items in the compound be single-vectors in the sequence, and that on decoding, the RNN doesn't have to conditionally track whether it is outputting `C` or `Cl`, for example. Doing so might even assist in increasing SMILES validity.

**Comment by maxhodak** [comment]
Not against increasing the charset size. What you're saying makes a lot of sense. But to the extent we're biasing the input with structure I'd much rather it was extracted automatically than via eg our judgment.

**Comment by dakoner** [comment]
What experiment would show semi-convincing evidence that one method or
another was "better"?

**Comment by dakoner** [comment]
On the issue of molecular representation, I have been interested in the issue of reversibly encoding graphs.  Not sure any of this has immediate relevance for this project, but I thought it interesting.

There is a graph toolkit, nauty, and it contains a 'generator' which can directly enumerate (and canonically label) all connected graphs of vertex degree N (the toolkit itself is for quickly detecting automorphism).  GDB-17 uses this to list all graphs, then substitutes in vertex atom number assignments (respecting atom valences) to generate all chemical structures.

nauty also includes a compact textual graph representation (graph6 and sparse6) which is reversible.  It doesn't include vertex or edge labels, which is a problem for what I was planning.   It does seem like you could train an autoencoder on graph6 strings (independent of molecular structure).  Some ideas I had:
1) not every graph6 encoding is a valid one but because all graphs can be enumerated, they could be mapped to a dense integer array using CMPH (minimal perfect hash).  It's not clear whether these could be used to guarantee generation of valid graph6 strings on decoding the latent space.

2) convert all molecular structures to their graph6 representation, and provide a side-input which is the atomic number vector (and any other per-atom or per-bond properties).  Train on the combination of those.  I don't know how to combine side-inputs-- possibly with the Merge layer in keras?

**Comment by dakoner** [comment]
As an initial step towards this, I wrote a script that converts between rdkit molecule and networkx graph, preserving attributes.  We preserve enough attributes from the rdkit molecule that we can convert the networkx graph back to an rdkit molecule, generating the same smiles string (testing on GDB-13 up to 12.smi, it correctly regenerates every SMILES string).

The networkx graph can then be written in graph6 format and any nauty tools can be used to work with it.  This permits, for example, mapping all the chemicals in ZINC into graph6, then identifying all chemicals with identical (no vertex label, just topologically equivalent) graphs.  Still trying to decide if this is really helpful or not.

**Comment by dakoner** [comment]
https://github.com/maxhodak/keras-molecules/pull/32 contains code that converts rdkit molecules to networkx graphs.  Valuable mainly because it demonstrates the minimal per-atom and per-bond attributes required to reconstruct an rdkit molecule.

**Comment by pechersky** [comment]
Thanks for coding up the rdkit-networkx code. The first experiment to run, in my opinion, would be to provide an adjacency matrix of (maxlen, maxlen), with 1s for edge between node_ij, so 0s on the diagonal. Then, feed these in as a separate input, pass through conv layers, probably with kernels of size 6-7.

Do you know if the graph6 string reps are depth or breadth first?

**Comment by dakoner** [comment]
The graph formats are documented here:
http://users.cecs.anu.edu.au/~bdm/data/formats.txt
 THere are tools in nauty that convert between the forms (amtog, listg)
although I find it easiest to have networkx generate the conversion with
read_graph6 and write_graph6.

They are compact bitmap representations, but with some bias added to put
the output in the ASCII space.  I am not sure whether they are depth or
breadth first- they appear to be bit-encodings of the adjacency matrix in
row major format.

You can easily make networkx output adjacency matrix, or populate a numpy
array directly.

**Comment by dakoner** [comment]
Going back to the cellular encoding, one obvious direction for the molecular ops would be SMARTS combined with Reaction SMILES.  You'd define the "simple" ops, AKA add/remove substituent, close/open ring, increase/decrease bond order, etc.  See http://www.rdkit.org/docs/GettingStartedInPython.html#chemical-transformations "replace substructures"

**Comment by pechersky** [comment]
Regarding encoding reactions, check out another Duvenaud paper:
http://pubs.acs.org/doi/pdf/10.1021/.

**Comment by pechersky** [comment]
https://dx.doi.org/10.1021/acscentsci.6b00219

**Comment by dakoner** [comment]
That's about reaction prediction, I'm proposing just using re-using the
basic reaction operations as molecular ops in an automata.

**Comment by maxhodak** [comment]
Both directions are super interesting. I've been thinking a lot about the synthetic accessibility problem and specifically the direction of seeing you can identify at least one likely synthetic route (and thus associated uncertainty).

Encoding molecules throughout using the basic reaction operations also seems definitely worth exploring.

**Comment by pechersky** [comment]
Regarding synthetic accessibility, check out these two papers (companions):
http://onlinelibrary.wiley.com/doi/10.1002/anie.201202209/full
http://onlinelibrary.wiley.com/doi/10.1002/ange.201202210/full

They try to enumerate all possible synthetic routes and how to optimize for shortest on cost, time, or availability of feedstocks.

Let's say we get a rich latent space that embeds structures soundly. I would imagine that "reactions" are some vectors in that space, more of a vector field, since I doubt that the direction of any such reaction would remain the same upon translation to a different part of the space.

Consider training a decoder on the space to learn a function: cLogP, for example. A small molecular perturbation of inserting an O (that forms a hydroxyl or carbonyl) is going to highly perturb the cLogP value.

With those two thoughts in mind, I feel like encoding molecules based on basic reaction operations, whether "synthetic chemistry" or "cellular molecular ops" might hurt or prevent learning other functions on the space. Or maybe not -- I don't have a strong intuition of how to validate this.

**Comment by maxhodak** [comment]
@pechersky can you send me an email? I can't find an email address for you. My contact info is on my GitHub profile. Thanks!
